### ISSUE TITLE
I would like to get the code representation through your model without doing downstream tasks

### ISSUE THREAD

**Issue by HosoyaKenn** [AwdHanPeng/TPTrans#2]
Hey！
I have a question  want to ask.
I would like to get the code representation through your model without doing downstream tasks, how should I run the code.
I wonder if it can generate csv file  so that I can do my own tasks，thank you！

**Comment by AwdHanPeng** [comment]
Hi, TPTrans is trained by MethodNaming task in this paper, so it cannot get code representation without downstream tasks, which is different to some self-supervised LLMs.
If you want to use TPTrans in your own tasks, try to modify the code of decoder in TPTrans/model/model.py, and also the data api in TPTrans/dataset/dataset.py.

**Comment by HosoyaKenn** [comment]
thank you for your reply !
I followed the steps you wrote to run it,But when I run the file multi_language_parse.py --language python,
![image](https://user-images.githubusercontent.com/62983214/227084504-e3c88243-86a1-4ebd-a03d-86796eb29e76.png)
Didn't have this problem when I ran other languages.
And when I run the file  _main.py_ ,
![image](https://user-images.githubusercontent.com/62983214/227084726-9c31be89-daba-4cfa-97d2-57ec8d0f1e5a.png)
Please tell me how to solve it

**Comment by AwdHanPeng** [comment]
Hi, the error about python parsing shows that some sample could not be parsed correctly.
So I guess the crux should be the 'terminal' var in the 64th line of multi_language_parser.py.
"assert l_[0] == r_[0]" is used to ensure the terminal is a variable-type token in python sample code, rather than a long string or comment (which may cross multi-lines). So you could try to debug at this line, and add the type of the current terminal into the dict of string_type[python] in 27 lines.

Just remove the "self.rp_sample = self.args.rp_sample", it seems a dead code.

**Comment by HosoyaKenn** [comment]
it works ,thank you!
